version: '3.8'
services:

  backend:
    image: backend:latest
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
    ports:
      - 8000:8000

  frontend:
    image: frontend:latest-amd64
    ports:
      - 80:80

  db:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=afiyyet
      - POSTGRES_PASSWORD=2vMNPU49Ep47HtYn
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432