export let menu = {
    currency: '₺',
    campaigns: [],
    categories: [{
        name: '\n  Kahvaltı  \n',
        products: [{
            name: 'Kahvaltı Tabağı',
            price: 39.0,
            description: 'Peynir tabağı, söğüş, siyah ve yeşil zeytin, reçel, tereyağ, bal, haşlanmış yumurta, salam, dana jambon, şefin ekmek sepeti ve 2 adet çay ile servis edilir. \xa0',
            likes: 0,
        },
            {
                name: 'Serpme Kahvaltı ( 2 Kişilik)',
                price: 90.0,
                description: 'Peynir tabağı, söğüş tabağı, siyah ve yeşil zeytin, çilek reçeli, bal - kaymak, \xa0sahanda iki göz yumurta, sigara böreği, salam, dana jambon, sucuk, şefin ekmek sepeti ve sınırsız çay ile servis edilir. \xa0',
                likes: 0,
            },
            {
                name: 'Pancake Kahvaltı Tabağı',
                price: 25.0,
                description: '3 adet pancake, nutella ve çay eşliğinde servis edilir.\xa0',
                likes: 0,
            },
            {name: 'Sade Omlet', price: 16.0, description: '', likes: 0},
            {name: 'Kaşarlı Omlet', price: 18.0, description: '', likes: 0},
            {name: 'Otlu Omlet', price: 19.0, description: '', likes: 0},
            {
                name: 'Sahanda Çift Göz Yumurta',
                price: 16.0,
                description: '',
                likes: 0,
            },
            {name: 'Sade Menemen', price: 20.0, description: '', likes: 0},
            {name: 'Kaşarlı Menemen', price: 22.0, description: '', likes: 0},
            {
                name: 'Dil Peynirli Tost',
                price: 18.0,
                description: 'Dil peyniri ve domates, patates tava eşliğinde servis edilir.\xa0',
                likes: 0,
            },
            {
                name: 'Sucuklu Tost',
                price: 19.0,
                description: 'Dil peyniri, sucuk, domates patates tava eşliğinde servis edilir.\xa0',
                likes: 0,
            },
            {
                name: 'Yengen Tost',
                price: 20.0,
                description: 'Dil peyniri, sucuk, domates ve ketçap ile patates tava eşliğinde servis edilir.\xa0',
                likes: 0,
            },
            {
                name: 'Dana Jambonlu Tost',
                price: 20.0,
                description: 'Dil peyniri, dana jambon domates ile patates tava eşliğinde servis edilir.\xa0',
                likes: 0,
            },
            {
                name: 'Beyaz Peynirli Tost',
                price: 19.0,
                description: 'Kepek ekmeğine beyaz peynir, domates patates tava eşliğinde servis edilir.\xa0',
                likes: 0,
            },
            {
                name: 'Nutella ve Kaymak',
                price: 23.0,
                description: '',
                likes: 0,
            }],
    },
        {
            name: '\n  Çorbalar  \n',
            products: [{
                name: 'Domates Çorbası',
                price: 12.0,
                description: 'Mozzarella peyniri ve kreton ekmek ile',
                likes: 0,
            },
                {
                    name: 'Günün Çorbası',
                    price: 12.0,
                    description: 'Her gün farklı bir çorba!',
                    likes: 0,
                }],
        },
        {
            name: '\n  Atıştırmalıklar  \n',
            products: [{
                name: 'Sigara Böreği',
                price: 20.0,
                description: 'Sweet chili sos ile 8 adet sigara böreği',
                likes: 0,
            },
                {
                    name: 'Mozzarella Sticks',
                    price: 22.0,
                    description: 'Patates tava ve cheddar sos ile 6 adet mozzarella sticks',
                    likes: 0,
                },
                {
                    name: 'Cajun Çöp Şiş',
                    price: 24.0,
                    description: 'Cajun baharatı ile hazırlanmış tavuk fileto, patates tava ve cheddar sos ile',
                    likes: 0,
                },
                {
                    name: 'Acılı Tavuk Kanatları',
                    price: 23.0,
                    description: 'Patates tava ve\xa0Louisiana sos ile 6 adet acılı tavuk kanadı',
                    likes: 0,
                },
                {
                    name: 'Karışık Ara Sıcak',
                    price: 34.0,
                    description: 'Mozzeralla sticks, cajun çöp şiş, sigara böreği, soğan halkası ve patates tava',
                    likes: 0,
                },
                {
                    name: 'Soğan Halkası',
                    price: 20.0,
                    description: 'Patates tava ve cheddar sos ile 6 adet soğan halkası',
                    likes: 0,
                },
                {name: 'Patates Tava', price: 19.0, description: '', likes: 0}],
        },
        {
            name: '\n  Dürümler  \n',
            products: [{
                name: 'Etli Mantarlı Dürüm',
                price: 32.0,
                description: 'Patates tava ile servis edilir.\xa0',
                likes: 0,
            },
                {
                    name: 'Tavuklu Mantalı Dürüm',
                    price: 28.0,
                    description: 'Patates tava ile servis edilir.\xa0',
                    likes: 0,
                },
                {
                    name: 'Köfteli Dürüm',
                    price: 30.0,
                    description: 'Patates tava ile servis edilir.\xa0',
                    likes: 0,
                },
                {
                    name: 'Beğendili Köfteli Dürüm',
                    price: 32.0,
                    description: 'Cheddar peyniri ve patlıcan beğendi. Patates tava ile servis edilir.\xa0',
                    likes: 0,
                },
                {
                    name: 'Sebzeli Peynirli Dürüm',
                    price: 25.0,
                    description: 'Patates tava ile servis edilir.\xa0',
                    likes: 0,
                }],
        },
        {
            name: '\n  Burgerler  \n',
            products: [{
                name: 'Klasik Burger',
                price: 32.0,
                description: 'Karamelize soğan ve domates sos',
                likes: 0,
            },
                {
                    name: 'Cheeseburger',
                    price: 34.0,
                    description: 'Cheddar peyniri, karamelize soğan ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Dana Jambonlu Burger',
                    price: 35.0,
                    description: 'Dana jambon, cheddar peyniri, mantar, karamelize soğan ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Füme Etli Mantarlı Burger',
                    price: 37.0,
                    description: 'Boşnak kuru et, cheddar peyniri, mantar, karamelize soğan ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Chicken Cheeseburger',
                    price: 30.0,
                    description: 'Izgara tavuk, cheddar peyniri, remoulade ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Mexican Beef Burger',
                    price: 39.0,
                    description: 'Acılı soğan kavurmalı biftek, cheddar peyniri ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Köri Soslu Burger',
                    price: 34.0,
                    description: 'Köri sos, cheddar peyniri ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Beğendili Burger',
                    price: 35.0,
                    description: 'Bostan patlıcan beğendi ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Fried Chicken Burger',
                    price: 32.0,
                    description: 'Kızarmış tavuk, cheddar peyniri, remoulade ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Kaserol Double Burger ( 400gr. )',
                    price: 52.0,
                    description: 'Cheddar peyniri, karamelize soğan ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Sucuk Burger',
                    price: 33.0,
                    description: 'Ev yapımı sucuk, dil peyniri, karamelize soğan ve domates sos',
                    likes: 0,
                },
                {
                    name: 'BBQ Burger',
                    price: 34.0,
                    description: 'Cheddar peyniri, kekik, barbekü sos ve karamelize soğan',
                    likes: 0,
                },
                {
                    name: 'Burger Ring',
                    price: 35.0,
                    description: 'Cheddar peyniri, soğan halkası, mayonez ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Dil Peynirli Burger',
                    price: 34.0,
                    description: 'Dil peyniri, karamelize soğan ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Cheddar Burger',
                    price: 35.0,
                    description: 'Cheddar soslu burger köftesi',
                    likes: 0,
                },
                {
                    name: 'Amerikan Burger',
                    price: 35.0,
                    description: 'Cheddar peyniri, kırmızı soğan, yeşillik, domates ve mayonez',
                    likes: 0,
                },
                {
                    name: 'Lokum Burger',
                    price: 46.0,
                    description: 'Bonfile lokum, cheddar peyniri ve\xa0karamelize soğan\xa0',
                    likes: 0,
                }],
        },
        {
            name: '\n  Pizza  \n',
            products: [{
                name: 'Margherita',
                price: 29.0,
                description: 'Mozzarella peynir ve domates sos',
                likes: 0,
            },
                {
                    name: 'Funghi',
                    price: 29.0,
                    description: 'Mantar,\xa0mozzarella peynir ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Vejeteryan',
                    price: 29.0,
                    description: 'Mevsim sebzeleri,\xa0mozzarella peynir ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Capricossa',
                    price: 36.0,
                    description: 'Dana jambon, mantar, yeşil biber,\xa0mozzarella peynir ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Piccante',
                    price: 38.0,
                    description: 'Sucuk, mantar, jalepeno,\xa0mozzarella peynir ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Ton Balıklı',
                    price: 35.0,
                    description: 'Ton balığı, kırmızı soğan, kapari,\xa0mozzarella peynir ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Hot Chili',
                    price: 37.0,
                    description: 'Sucuk, mantar, jalepeno, chilli sos, mozzarella peynir ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Misket Köfteli',
                    price: 37.0,
                    description: 'Misket köfte, mantar, mısır, mozzarella peyniri ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Füme Etli Kestane Mantarlı',
                    price: 45.0,
                    description: 'Boşnak kuru et, kestane mantarı, mozzarella peynir ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Toronto',
                    price: 40.0,
                    description: 'Salam, sucuk, zeytin, mısır, yeşil biber, mozzarella peynir ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Kepekli Pizza',
                    price: 32.0,
                    description: 'Cherry domates, kekik, light beyaz peynir ve siyah zeytin\xa0',
                    likes: 0,
                }],
        },
        {
            name: '\n  Çocuk Menüsü  \n',
            products: [{
                name: 'Mini Pizza',
                price: 25.0,
                description: 'Mozzarella peynir, mısır, sosis',
                likes: 0,
            },
                {
                    name: 'Mini Burger',
                    price: 25.0,
                    description: 'Üç adet köfteli mini burger',
                    likes: 0,
                },
                {
                    name: 'Misket Köfte',
                    price: 23.0,
                    description: 'Şişte köfte ve patates tava',
                    likes: 0,
                },
                {
                    name: 'Mini Sosis',
                    price: 22.0,
                    description: 'Izgara mini sosis tabağı',
                    likes: 0,
                }],
        },
        {
            name: '\n  Makarna  \n',
            products: [{
                name: 'Spaghetti Bolognese',
                price: 32.0,
                description: 'Kıymalı domates sos ve fesleğen',
                likes: 0,
            },
                {
                    name: 'Penne Al Arrabbiata',
                    price: 30.0,
                    description: 'Domates sos ve acı biber',
                    likes: 0,
                },
                {
                    name: 'Sebzeli Domates Soslu Penne',
                    price: 30.0,
                    description: 'Mantar, fasülye, kapya biber ve domates sos',
                    likes: 0,
                },
                {
                    name: 'Kremalı Mantarlı Fettucine',
                    price: 33.0,
                    description: 'Kestane mantarı, krema ve fesleğen sos',
                    likes: 0,
                },
                {
                    name: 'Fettucine Chicken Alfredo',
                    price: 37.0,
                    description: 'Izgara tavuk, közlenmiş biber ve krema',
                    likes: 0,
                },
                {
                    name: 'Fresh Penne',
                    price: 34.0,
                    description: 'Pesto sos, beyaz peynir, dilim zeytin, mısır ve yeşil biber',
                    likes: 0,
                }],
        },
        {
            name: '\n  Ev Yapımı Mantılar  \n',
            products: [{
                name: 'Kayseri Mantısı',
                price: 34.0,
                description: 'Ev yapımı Kayseri mantısı',
                likes: 0,
            },
                {
                    name: 'Özel Mantı',
                    price: 38.0,
                    description: 'Bonfile parçaları ile hazırlanmış özel soslu mantı',
                    likes: 0,
                },
                {
                    name: 'Çıtır Mantı',
                    price: 34.0,
                    description: 'Ev yapımı kızarmış mantı',
                    likes: 0,
                }],
        },
        {
            name: '\n  Salata  \n',
            products: [{
                name: 'Roka Domates Mozzarella',
                price: 30.0,
                description: 'Taze roka, domates, mısır, parmesan peyniri',
                likes: 0,
            },
                {
                    name: 'Hoisin Soslu Tavuk Salata',
                    price: 32.0,
                    description: 'Karamelize soğan, Jülyen tavuk parçaları, mantar ve biber çeşitleri',
                    likes: 0,
                },
                {
                    name: 'Biftek Salata (Oyster Soslu)',
                    price: 39.0,
                    description: 'Karamelize soğan, Jülyen tavuk parçaları, mantar ve biber çeşitleri',
                    likes: 0,
                },
                {
                    name: 'Klasik Sezar Salata',
                    price: 33.0,
                    description: 'Sezar sos, kruton ve körpe marul',
                    likes: 0,
                },
                {
                    name: 'Tavuklu Sezar Salata',
                    price: 37.0,
                    description: 'Izgara tavuk, sezar sos, bruton ve körpe marul',
                    likes: 0,
                },
                {
                    name: 'Beyaz Peynirli Izgara Sebze Salata',
                    price: 33.0,
                    description: 'Akdeniz yeşilliği, ızgara sebze ve beyaz peynir',
                    likes: 0,
                },
                {
                    name: 'Izgara Hellim Salata',
                    price: 36.0,
                    description: 'Akdeniz yeşilliği, sebze kavurması ve ızgara hellim',
                    likes: 0,
                },
                {
                    name: 'Kızarmış Tavuklu Salata',
                    price: 33.0,
                    description: 'Karışık yeşillik, ballı hardal sos ve kajun baharatlı tavuk',
                    likes: 0,
                },
                {
                    name: 'Tulum Peynirli Salata',
                    price: 37.0,
                    description: 'Domates, salatalık, kinoa, taze nane, maydanoz ve zeytinyağı\xa0',
                    likes: 0,
                },
                {
                    name: 'Ton Balıklı Salata',
                    price: 38.0,
                    description: 'Rokalı akdeniz yeşilliği, ton balığı, mısır, kapari çiçeği ve kırmızı soğan\xa0',
                    likes: 0,
                }],
        },
        {
            name: '\n  Diyet Menü  \n',
            products: [{
                name: 'Naneli Yoğurtlu Izgara Sebze',
                price: 32.0,
                description: 'Patlıcan, kabak, mantar, fasülye ve biber çeşitleri',
                likes: 0,
            },
                {
                    name: 'Sebzeli Kepekli Penne',
                    price: 32.0,
                    description: 'Mantar, fasülye ve biber çeşitleri',
                    likes: 0,
                },
                {
                    name: 'Diyet Tavuk Izgara',
                    price: 37.0,
                    description: 'Salata, haşlanmış sebze ve naneli yoğurt',
                    likes: 0,
                }],
        },
        {
            name: '\n  Izgara Tavuklar  \n',
            products: [{
                name: 'Adaçayı Limon Soslu Tavuk',
                price: 39.0,
                description: 'Kumpir patates ve mantarlı ıspanak kavurması ile',
                likes: 0,
            },
                {
                    name: 'Mantar Soslu Piliç Izgara',
                    price: 39.0,
                    description: 'Kumpir patates ve ıspanak kavurması ile',
                    likes: 0,
                },
                {
                    name: 'Tavuk Schitzel',
                    price: 33.0,
                    description: 'Parmak patates ve mini salata ile',
                    likes: 0,
                },
                {
                    name: 'Ispanaklı Peynirli Piliç Gretine',
                    price: 39.0,
                    description: 'Dilim mozzarella ve taze ıspanak',
                    likes: 0,
                },
                {
                    name: 'Mantar Soslu Tavuk Schnitzel',
                    price: 39.0,
                    description: 'Parmak patates ve mini salata ile',
                    likes: 0,
                },
                {
                    name: 'Köri Soslu Tavuk Izgara',
                    price: 39.0,
                    description: 'Kumpir patates ve mantarlı ıspanak kavurması ile',
                    likes: 0,
                },
                {
                    name: 'Taze Kekikli Tavuk But',
                    price: 39.0,
                    description: 'Parmak patates ve mantarlı ıspanak kavurması ile salata',
                    likes: 0,
                },
                {
                    name: 'Barbekü Piliç Izgara',
                    price: 38.0,
                    description: 'Kumpir patates ve mini salata ile',
                    likes: 0,
                },
                {
                    name: 'Sebzeli Peynirli Piliç Gretine',
                    price: 39.0,
                    description: 'Dilim mozzarella ve mevsim sebzeleri',
                    likes: 0,
                },
                {
                    name: 'Barbekü Tavuk Kanat',
                    price: 38.0,
                    description: 'Parmak patates ve mini salata ile',
                    likes: 0,
                }],
        },
        {
            name: '\n  Izgara Etler  \n',
            products: [{
                name: 'Izgara Bonfile (250-300gr.)',
                price: 80.0,
                description: 'Kumpir patates ve ıspanak kavurması ile',
                likes: 0,
            },
                {
                    name: 'Bonfile Dana Lokum (200gr.)',
                    price: 82.0,
                    description: 'Kumpir patates ve mantarlı ıspanak kavurması ile',
                    likes: 0,
                },
                {
                    name: 'Dana Antrikot (320gr.)',
                    price: 85.0,
                    description: 'Kumpir patates ve mantarlı ıspanak kavurması ile',
                    likes: 0,
                },
                {
                    name: 'Mantar Soslu Bonfile',
                    price: 80.0,
                    description: 'Patates tava ve ıspanak kavurması ile',
                    likes: 0,
                },
                {
                    name: 'Beğendili Köfte',
                    price: 40.0,
                    description: 'Tereyağlı bostan patlıcanlı beğendi üzerine ev yapımı ızgara köfte',
                    likes: 0,
                },
                {
                    name: 'Yoğurtlu Kebap',
                    price: 48.0,
                    description: 'Taze pide, kibrit patates, köfte, külbastı, domates ve tereyağ sos',
                    likes: 0,
                },
                {
                    name: 'Hünkarbeğendi',
                    price: 48.0,
                    description: 'Dana kuşbaşı ve tereyağlı bostan patlıcanlı beğendi',
                    likes: 0,
                },
                {
                    name: 'Izgara Köfte',
                    price: 39.0,
                    description: 'Bulgur pilavı, mini salata, patates tava ve salsa sos',
                    likes: 0,
                },
                {
                    name: 'Biftek Külbastı',
                    price: 52.0,
                    description: 'Kumpir patates ve mantarlı ıspanak kavurması ile',
                    likes: 0,
                }],
        },
        {
            name: '\n  Fajitas  \n',
            products: [{
                name: 'Etli Fajitas',
                price: 54.0,
                description: 'Sour cream, salsa ve guacamole sos ile',
                likes: 0,
            },
                {
                    name: 'Tavuklu Fajitas',
                    price: 49.0,
                    description: 'Sour cream, salsa ve guacamole sos ile',
                    likes: 0,
                }],
        },
        {
            name: '\n  Quesadillas  \n',
            products: [{
                name: 'Sebzeli Quesadillas',
                price: 32.0,
                description: 'Sour cream, salsa ve guacamole sos ile',
                likes: 0,
            },
                {
                    name: 'Biftekli Quesadillas',
                    price: 35.0,
                    description: 'Sour cream, salsa ve guacamole sos ile',
                    likes: 0,
                },
                {
                    name: 'Tavuklu Quesadillas',
                    price: 32.0,
                    description: 'Sour cream, salsa ve guacamole sos ile',
                    likes: 0,
                }],
        },
        {
            name: '\n  Noodle  \n',
            products: [{
                name: 'Sebzeli Köri Soslu Noodle',
                price: 32.0,
                description: 'Kabak, havuç ve kırmızı biber',
                likes: 0,
            },
                {
                    name: 'Acılı Sebzeli Tavuklu Noodle',
                    price: 33.0,
                    description: 'Chilli sos, tavuk, kabak, havuç ve kırmızı biber',
                    likes: 0,
                },
                {
                    name: 'Dalian Soslu Biftekli Noodle',
                    price: 38.0,
                    description: 'Biftek, acı tatlı sos, kabak, havuç ve kırmızı biber',
                    likes: 0,
                }],
        },
        {
            name: '\n  Güveçler  \n',
            products: [{
                name: 'Tavuklu Güveç',
                price: 37.0,
                description: 'Arpacık soğan, sarımsak, tatlı sivri biber ve domates',
                likes: 0,
            },
                {
                    name: 'Çoban Kavurma',
                    price: 57.0,
                    description: 'Dana kuşbaşı, arpacık soğan, soğan, sivri biber ve domates',
                    likes: 0,
                },
                {
                    name: 'Güveçte Sebze Kavurma',
                    price: 37.0,
                    description: 'Arpacık soğan, sarımsak, patlıcan, kabak, fasülye, sivri biber ve domates',
                    likes: 0,
                },
                {
                    name: 'Tavuk Budu Çoban Kavurma',
                    price: 40.0,
                    description: 'Arpacık soğan, sarımsak, patlıcan, kabak, fasülye, sivri biber ve domates',
                    likes: 0,
                }],
        },
        {
            name: '\n  Tatlılar  \n',
            products: [{
                name: 'Ballı Badem',
                price: 25.0,
                description: 'Bir top dondurma ve file badem ile',
                likes: 0,
            },
                {
                    name: 'Dondurmalı Brownie',
                    price: 23.0,
                    description: 'İki brownie katı arası dondurma',
                    likes: 0,
                },
                {
                    name: 'Çikolatalı Sufle',
                    price: 23.0,
                    description: 'Bir top dondurma ile sıcak çikolatalı sufle',
                    likes: 0,
                },
                {
                    name: 'Dondurmalı Waffle',
                    price: 28.0,
                    description: 'Nutella, muz, çilek, kivi ve bir top dondurma ile',
                    likes: 0,
                },
                {
                    name: 'Meyveli Pancake Katları',
                    price: 29.0,
                    description: 'Nutella, muz ve çilek',
                    likes: 0,
                },
                {
                    name: 'Cheescake',
                    price: 25.0,
                    description: 'Limonlu / Frambuazlı / Çikolatalı',
                    likes: 0,
                },
                {name: 'Dondurma', price: 16.0, description: 'Sade', likes: 0}],
        },
        {
            name: '\n  Soğuk İçecekler  \n',
            products: [{
                name: 'Coca Cola',
                price: 8.0,
                description: 'Orijinal / Light / Şekersiz',
                likes: 0,
            },
                {
                    name: 'Fuse Tea',
                    price: 8.0,
                    description: 'Limon / Şeftali',
                    likes: 0,
                },
                {name: 'Fanta', price: 8.0, description: '', likes: 0},
                {name: 'Sprite', price: 8.0, description: '', likes: 0},
                {
                    name: 'Cappy Meyve Suyu',
                    price: 8.0,
                    description: 'Şeftali / Vişne',
                    likes: 0,
                },
                {
                    name: 'Schweppes Mandalina',
                    price: 8.0,
                    description: '',
                    likes: 0,
                },
                {name: 'Niğde Gazozu', price: 8.0, description: '', likes: 0},
                {name: 'Ayran', price: 8.0, description: '', likes: 0},
                {name: 'Fesleğenli Ayran', price: 9.0, description: '', likes: 0},
                {name: 'Naneli Ayran', price: 9.0, description: '', likes: 0},
                {name: 'Kekikli Ayran', price: 9.0, description: '', likes: 0},
                {name: 'Su', price: 5.0, description: '', likes: 0},
                {
                    name: 'Sırma Exclusive Maden Suyu',
                    price: 7.0,
                    description: '',
                    likes: 0,
                }],
        },
        {
            name: '\n  Ev Yapımı Limonatalar  \n',
            products: [{
                name: 'Klasik',
                price: 15.0,
                description: '',
                likes: 0,
            },
                {
                    name: 'Zencefil Okaliptüs',
                    price: 16.0,
                    description: '',
                    likes: 0,
                },
                {name: 'Fesleğen', price: 16.0, description: '', likes: 0},
                {name: 'Yeşil Elma', price: 16.0, description: '', likes: 0},
                {name: 'Karadut', price: 16.0, description: '', likes: 0},
                {name: 'Çilek', price: 16.0, description: '', likes: 0},
                {name: 'Çilek', price: 16.0, description: '', likes: 0},
                {name: 'Mango', price: 16.0, description: '', likes: 0},
                {name: 'Orman Meyveleri', price: 18.0, description: '', likes: 0}],
        },
        {
            name: '\n  Sıcak İçecekler  \n',
            products: [{name: 'Mocha', price: 16.0, description: '', likes: 0},
                {name: 'Cappucino', price: 13.0, description: '', likes: 0},
                {name: 'Espresso', price: 12.0, description: '', likes: 0},
                {name: 'Double Espresso', price: 14.0, description: '', likes: 0},
                {
                    name: 'Aromalı Kahve',
                    price: 12.0,
                    description: 'Fındık / Hindistan Cevizi / Vanilya',
                    likes: 0,
                },
                {name: 'Filtre Kahve', price: 14.0, description: '', likes: 0},
                {name: 'Americano', price: 14.0, description: '', likes: 0},
                {name: 'Latte', price: 14.0, description: '', likes: 0},
                {name: 'Ice Cream Latte', price: 16.0, description: '', likes: 0},
                {name: 'Macchiato', price: 10.0, description: '', likes: 0},
                {name: 'Caramel Macchiato', price: 16.0, description: '', likes: 0},
                {name: 'Sıcak Çikolata', price: 14.0, description: '', likes: 0},
                {name: 'Türk Kahvesi', price: 10.0, description: '', likes: 0},
                {name: 'Salep', price: 14.0, description: '', likes: 0},
                {name: 'Demleme Çay', price: 5.0, description: '', likes: 0},
                {
                    name: 'White Chocolate Mocha',
                    price: 16.0,
                    description: '',
                    likes: 0,
                }],
        },
        {
            name: '\n  Soğuk Kahveler  \n',
            products: [{
                name: 'Ice Latte',
                price: 16.0,
                description: '',
                likes: 0,
            },
                {name: 'Ice Latte Caramel', price: 16.0, description: '', likes: 0},
                {name: 'Ice Mocha', price: 16.0, description: '', likes: 0},
                {name: 'Frappe', price: 16.0, description: '', likes: 0},
                {name: 'Coconut Chocolate', price: 16.0, description: '', likes: 0},
                {name: 'Ice Americano', price: 16.0, description: '', likes: 0}],
        },
        {
            name: '\n  Taze Meyve Suları  \n',
            products: [{
                name: 'Portakal',
                price: 15.0,
                description: '',
                likes: 0,
            },
                {name: 'Yeşil Elma', price: 15.0, description: '', likes: 0},
                {name: 'Havuç', price: 15.0, description: '', likes: 0},
                {name: 'Karışık', price: 17.0, description: '', likes: 0}],
        },
        {
            name: '\n  Flings  \n',
            products: [{name: 'Çilek', price: 17.0, description: '', likes: 0},
                {name: 'Yeşil Elma', price: 18.0, description: '', likes: 0},
                {name: 'Orman Meyveleri', price: 18.0, description: '', likes: 0},
                {name: 'Mango', price: 17.0, description: '', likes: 0},
                {name: 'Karadut', price: 17.0, description: '', likes: 0}],
        },
        {
            name: '\n  Milkshake  \n',
            products: [{name: 'Çilek', price: 19.0, description: '', likes: 0},
                {name: 'Muz', price: 19.0, description: '', likes: 0},
                {name: 'Vanilya', price: 17.0, description: '', likes: 0},
                {name: 'Karamel', price: 19.0, description: '', likes: 0},
                {name: 'Çikolata', price: 19.0, description: '', likes: 0},
                {name: 'Karadut', price: 19.0, description: '', likes: 0},
                {name: 'Orman Meyveleri', price: 19.0, description: '', likes: 0}],
        },
        {
            name: '\n  Frozen  \n',
            products: [{name: 'Çilek', price: 16.0, description: '', likes: 0},
                {name: 'Yeşil Elma', price: 19.0, description: '', likes: 0},
                {name: 'Orman Meyveleri', price: 15.0, description: '', likes: 0},
                {name: 'Mango', price: 15.0, description: '', likes: 0},
                {name: 'Karadut', price: 15.0, description: '', likes: 0}],
        },
        {
            name: '\n  Bitki Çayları (Demlik)  \n',
            products: [{
                name: 'Özel Harman Fincan Çay',
                price: 10.0,
                description: '',
                likes: 0,
            },
                {name: 'Yeşil Çay', price: 15.0, description: '', likes: 0},
                {
                    name: 'Yaseminli Yeşil Çay',
                    price: 15.0,
                    description: '',
                    likes: 0,
                },
                {
                    name: 'Nane - Limon Yeşil Çay',
                    price: 15.0,
                    description: '',
                    likes: 0,
                },
                {name: 'Papatya Çayı', price: 15.0, description: '', likes: 0},
                {name: 'Ada Çayı', price: 15.0, description: '', likes: 0},
                {
                    name: 'Dr. Kaserol Karışık Bitki Çayı',
                    price: 17.0,
                    description: '',
                    likes: 0,
                },
                {name: 'Elma - Tarçın', price: 15.0, description: '', likes: 0},
                {name: 'Zencefil - Limon', price: 15.0, description: '', likes: 0},
                {name: 'Ihlamur', price: 16.0, description: '', likes: 0},
                {
                    name: 'Doğal Taneli Karadut Çayı',
                    price: 16.0,
                    description: '',
                    likes: 0,
                },
                {
                    name: 'Doğal Taneli Elma Çayı',
                    price: 16.0,
                    description: '',
                    likes: 0,
                },
                {
                    name: 'Doğal Taneli Nar Çayı',
                    price: 16.0,
                    description: '',
                    likes: 0,
                }],
        }],
};
