import {Injectable} from '@angular/core';
import {Category, Item} from '../model/models';

@Injectable({
    providedIn: 'root',
})
export class MenuService {

    categories = [
        {
            id: 66040,
            name: 'Донеры',
            image: 'http://chocofood.kz/media/site/restaurants/food/logo/2020/09/07/food_MhtEjhm.png',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 2,
            isActive: 1,
            foodCount: 26,
            isAlcohol: false,
        },
        {
            id: 66044,
            name: 'Горячие блюда',
            image: 'http://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_rNJf6Ug.png',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 3,
            isActive: 1,
            foodCount: 6,
            isAlcohol: false,
        },
        {
            id: 66042,
            name: 'Пицца',
            image: 'http://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_EH1kxYo.png',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 4,
            isActive: 1,
            foodCount: 7,
            isAlcohol: false,
        },
        {
            id: 66039,
            name: 'Гарниры',
            image: 'http://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_tNK2Eda.png',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 5,
            isActive: 1,
            foodCount: 1,
            isAlcohol: false,
        },
        {
            id: 66048,
            name: 'Супы',
            image: 'http://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_XRiRcpe.png',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 6,
            isActive: 1,
            foodCount: 3,
            isAlcohol: false,
        },
        {
            id: 66043,
            name: 'Салаты',
            image: 'http://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_LEph1p6.png',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 7,
            isActive: 1,
            foodCount: 5,
            isAlcohol: false,
        },
        {
            id: 66047,
            name: 'Блины',
            image: 'http://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_HaiCWcV.png',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 8,
            isActive: 1,
            foodCount: 10,
            isAlcohol: false,
        },
        {
            id: 66045,
            name: 'Хлеб/Соус',
            image: 'https://e3.edimdoma.ru/data/recipes/0004/3055/43055-ed4_wide.jpg?1468552193',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 9,
            isActive: 1,
            foodCount: 5,
            isAlcohol: false,
        },
        {
            id: 66041,
            name: 'Напитки',
            image: 'http://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_nWgfxKl.png',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 10,
            isActive: 1,
            foodCount: 13,
            isAlcohol: false,
        },
        {
            id: 66051,
            name: 'Лимонады',
            image: 'https://media-cdn.tripadvisor.com/media/photo-s/13/22/a8/15/caption.jpg',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 11,
            isActive: 1,
            foodCount: 14,
            isAlcohol: false,
        },
        {
            id: 66052,
            name: 'Коктейли',
            image: 'https://delimanoua.azureedge.net/media/article/image/cache/580x436/a/-/a-25472_1.jpg',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 12,
            isActive: 1,
            foodCount: 7,
            isAlcohol: false,
        },
        {
            id: 66053,
            name: 'Фреши',
            image: 'https://blog.allo.ua/wp-content/uploads/Freshi.jpg',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 13,
            isActive: 1,
            foodCount: 2,
            isAlcohol: false,
        },
        {
            id: 66054,
            name: 'Мохито',
            image: 'https://vxlam.ru/wp-content/uploads/2018/07/mojito.jpg',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 14,
            isActive: 1,
            foodCount: 4,
            isAlcohol: false,
        },
        {
            id: 66055,
            name: 'Смузи',
            image: 'https://www.iecavnieks.lv/files/a2017/001.jpg',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 15,
            isActive: 1,
            foodCount: 4,
            isAlcohol: false,
        },
        {
            id: 66056,
            name: 'Кофе',
            image: 'https://e0.edimdoma.ru/data/ingredients/0000/6579/6579-ed4_wide.jpg?1515762698',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 16,
            isActive: 1,
            foodCount: 9,
            isAlcohol: false,
        },
        {
            id: 66049,
            name: 'Бургеры',
            image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR7EVodj5NQhCPmryLJ6joGGIDQxczHHYWjYw&usqp=CAU',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 17,
            isActive: 1,
            foodCount: 2,
            isAlcohol: false,
        },
        {
            id: 66050,
            name: 'Комбо',
            image: 'https://www.edaedet.ru/upload/iblock/d99/d99903fc22748054808ad4b6f824c203.jpg',
            items: [],
            content: '',
            restaurant: 2412,
            parent: 0,
            position: 18,
            isActive: 1,
            foodCount: 1,
            isAlcohol: false,
        },
    ];
    products = [
        {
            id: 653238,
            name: 'Окрошка',
            image: '',
            category: 66048,
            content: '',
            ingredients: '',
            price: 790.0,
            discountPrice: 790.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653213,
            name: 'Халапеньо',
            image: '',
            category: 66045,
            content: '',
            ingredients: '',
            price: 100.0,
            discountPrice: 100.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653263,
            name: 'Bueno Milkshake 0,33 л',
            image: '',
            category: 66052,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653226,
            name: 'Блины со сгущенкой',
            image: 'https://thumb.chocofood.kz/suKdSnEIS87i0ezSP0nj0bjep9U=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_dstF6LI.png',
            category: 66047,
            content: '',
            ingredients: '',
            price: 590.0,
            discountPrice: 590.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653228,
            name: 'Блины с сыром',
            image: '',
            category: 66047,
            content: '',
            ingredients: '',
            price: 590.0,
            discountPrice: 590.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653229,
            name: 'Блины с курицей и грибами',
            image: '',
            category: 66047,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653222,
            name: 'Блины с m&ms',
            image: 'https://thumb.chocofood.kz/Mm-oHbso0uA5nXEOA1H4vVugqR4=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_HaiCWcV.png',
            category: 66047,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653223,
            name: 'Блины Зимняя Вишня',
            image: 'https://thumb.chocofood.kz/e0dc1eym-RqQ8x8cjm5UYdTsmeE=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_0filjYS.png',
            category: 66047,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653224,
            name: 'Блины с творогом',
            image: 'https://thumb.chocofood.kz/Njn2DlomeQGHjpE2wfjdT3RuWg8=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_Pd78cNX.png',
            category: 66047,
            content: '',
            ingredients: '',
            price: 690.0,
            discountPrice: 690.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653225,
            name: 'Блины с мёдом и грецкими орехами',
            image: 'https://thumb.chocofood.kz/FaLwcnYE-Sj25MX-5Jw9zkMk2-U=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_RQXl5H8.png',
            category: 66047,
            content: '',
            ingredients: '',
            price: 690.0,
            discountPrice: 690.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653231,
            name: 'Блины Баунти',
            image: 'https://thumb.chocofood.kz/am8b7jWOwmHom02pdli2NVFCi3c=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_HI0LSQf.png',
            category: 66047,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653234,
            name: 'Блин Тропик',
            image: 'https://thumb.chocofood.kz/Os4ZV49VocpAzuLly4NycadA4NY=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_GlMZM1Y.png',
            category: 66047,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653235,
            name: 'Блины с бананом и шоколадом',
            image: '',
            category: 66047,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653127,
            name: 'Картофель фри',
            image: 'https://thumb.chocofood.kz/5m4fLniFQjBvNNpQAfrnaxsyyx4=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_tNK2Eda.png',
            category: 66039,
            content: '',
            ingredients: '',
            price: 490.0,
            discountPrice: 490.0,
            position: 1,
            isActive: 1,
            note: 'popular',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653256,
            name: 'Лимонад-черника-малина 1 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 1240.0,
            discountPrice: 1240.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653240,
            name: 'Zheka’s hot angus burger',
            image: 'https://thumb.chocofood.kz/sGY8XUG6-xpl7qmxjhgKWJ2pruw=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_YdLd1vz.png',
            category: 66049,
            content: '',
            ingredients: '',
            price: 1390.0,
            discountPrice: 1390.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653184,
            name: 'Flash up Energy/Berry mix 0,45 л',
            image: '',
            category: 66041,
            content: '',
            ingredients: '',
            price: 390.0,
            discountPrice: 390.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653269,
            name: 'Эстрагон 0,4 л',
            image: '',
            category: 66054,
            content: '',
            ingredients: '',
            price: 790.0,
            discountPrice: 790.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653282,
            name: 'Ice Latte',
            image: '',
            category: 66056,
            content: '',
            ingredients: '',
            price: 790.0,
            discountPrice: 790.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653273,
            name: 'Смузи ягодный 0,33 л',
            image: '',
            category: 66055,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653198,
            name: 'Фруктовый салат',
            image: '',
            category: 66043,
            content: '',
            ingredients: '',
            price: 1090.0,
            discountPrice: 1090.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653242,
            name: 'Flash up COMBO (любой донер + flash up energy)',
            image: '',
            category: 66050,
            content: '',
            ingredients: '',
            price: 1180.0,
            discountPrice: 1180.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653190,
            name: 'Пицца донер Ассорти',
            image: 'https://thumb.chocofood.kz/AD8DPFYpFeXTo1-UNMJZecyvV0Y=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_mbRNDjx.png',
            category: 66042,
            content: '',
            ingredients: '',
            price: 1890.0,
            discountPrice: 1890.0,
            position: 1,
            isActive: 1,
            note: 'n/a',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 722651,
            name: 'Salam донер 2',
            image: 'https://thumb.chocofood.kz/cPSA3coIkoR5P4ZEKM27rUyTB0E=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/09/07/food_MhtEjhm.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1590.0,
            discountPrice: 1590.0,
            position: 1,
            isActive: 1,
            note: 'new',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653208,
            name: 'Лагман с джусаем',
            image: '',
            category: 66044,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653265,
            name: 'Яблоко 0,25 л',
            image: '',
            category: 66053,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 1,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653183,
            name: 'Flash up Energy/Mojito 0,45 л',
            image: '',
            category: 66041,
            content: '',
            ingredients: '',
            price: 390.0,
            discountPrice: 390.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653272,
            name: 'Kiwi Fusion 0,33 л',
            image: '',
            category: 66055,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 722650,
            name: 'Salam донер 1,5',
            image: 'https://thumb.chocofood.kz/VlPLwIa2qWFqd0wiZ22PFuSBizI=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/09/07/food_wqheh2S.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1190.0,
            discountPrice: 1190.0,
            position: 2,
            isActive: 1,
            note: 'new',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653199,
            name: 'Свежий салат',
            image: 'https://thumb.chocofood.kz/xUVDZkVg7zaz4V5aVHJ_5XFocCs=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_rlUCru5.png',
            category: 66043,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653201,
            name: 'Плов в коробке 300 гр',
            image: 'https://thumb.chocofood.kz/G5ggr71DsiERnOmYmUmXCBaiuc8=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_dTLOiGo.png',
            category: 66044,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653204,
            name: 'Гуйру лагман (острый)',
            image: 'https://thumb.chocofood.kz/h4SEYTHOV8aSkE_t962-afWZqJ4=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_rNJf6Ug.png',
            category: 66044,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653205,
            name: 'Гуйру лагман',
            image: 'https://thumb.chocofood.kz/wgPRhw1RsesGR46U1ku4-s8g8Zc=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_yDhRcZe.png',
            category: 66044,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653206,
            name: 'Цомян-Гуйру',
            image: 'https://thumb.chocofood.kz/6MAeizcFksq_v88J7YBvzXLwH78=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_8yE4SnO.png',
            category: 66044,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653207,
            name: 'Плов 300 гр',
            image: 'https://thumb.chocofood.kz/_DizIB88B4fN4xFLA8TfMMLFea0=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_QlVVamq.png',
            category: 66044,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653239,
            name: 'Чечевичный суп',
            image: '',
            category: 66048,
            content: '',
            ingredients: '',
            price: 790.0,
            discountPrice: 790.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653196,
            name: 'Салат Zheka’s',
            image: 'https://thumb.chocofood.kz/aMPCamPhCrVWMW2mvWh7qJfNP-A=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_LEph1p6.png',
            category: 66043,
            content: '',
            ingredients: '',
            price: 1190.0,
            discountPrice: 1190.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653281,
            name: 'Раф',
            image: '',
            category: 66056,
            content: '',
            ingredients: '',
            price: 790.0,
            discountPrice: 790.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653264,
            name: 'Апельсин 0,25 л',
            image: '',
            category: 66053,
            content: '',
            ingredients: '',
            price: 1090.0,
            discountPrice: 1090.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653212,
            name: 'Соус «Salsa»',
            image: '',
            category: 66045,
            content: '',
            ingredients: '',
            price: 100.0,
            discountPrice: 100.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653236,
            name: 'Куриный суп',
            image: 'https://thumb.chocofood.kz/9_LorX8E7soV0OUWgmurK0ELAzA=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_XRiRcpe.png',
            category: 66048,
            content: '',
            ingredients: '',
            price: 790.0,
            discountPrice: 790.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653192,
            name: 'Любимая пицца Жеки',
            image: 'https://thumb.chocofood.kz/QpCTY77Fxf1vHIIaY1kg9iDO-9U=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_EH1kxYo.png',
            category: 66042,
            content: '',
            ingredients: '',
            price: 1790.0,
            discountPrice: 1790.0,
            position: 2,
            isActive: 1,
            note: 'n/a',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653197,
            name: 'Салат Ачичук',
            image: 'https://thumb.chocofood.kz/-eDMjM6wyUDhOaa8pRkuhJw7ZU8=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_PFZyVNa.png',
            category: 66043,
            content: '',
            ingredients: '',
            price: 590.0,
            discountPrice: 590.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653268,
            name: 'Черника 0,4 л',
            image: '',
            category: 66054,
            content: '',
            ingredients: '',
            price: 790.0,
            discountPrice: 790.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653262,
            name: 'Snickers Milkshake 0,33 л',
            image: '',
            category: 66052,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653195,
            name: 'Салат "Цезарь" с курицей',
            image: '',
            category: 66043,
            content: '',
            ingredients: '',
            price: 1290.0,
            discountPrice: 1290.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653255,
            name: 'Лимонад-черника-малина 0,5 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 740.0,
            discountPrice: 740.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653241,
            name: 'Zheka’s angus burger',
            image: 'https://thumb.chocofood.kz/5ErU7iPLaz6TFlUH-AgiXc9Hnkc=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_Z21zyrz.png',
            category: 66049,
            content: '',
            ingredients: '',
            price: 1390.0,
            discountPrice: 1390.0,
            position: 2,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653267,
            name: 'Клубника 0,4 л',
            image: '',
            category: 66054,
            content: '',
            ingredients: '',
            price: 790.0,
            discountPrice: 790.0,
            position: 3,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653209,
            name: 'Сырный соус',
            image: '',
            category: 66045,
            content: '',
            ingredients: '',
            price: 150.0,
            discountPrice: 150.0,
            position: 3,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653219,
            name: 'Медовик',
            image: '',
            category: 66046,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 3,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 722649,
            name: 'Salam донер',
            image: 'https://thumb.chocofood.kz/1QRAllRT3dMv35r6zBcVF_rUd4o=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/09/07/food_GHQQsSE.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 3,
            isActive: 1,
            note: 'new',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653182,
            name: 'Классический Ice Tea 1 л',
            image: '',
            category: 66041,
            content: '',
            ingredients: '',
            price: 1190.0,
            discountPrice: 1190.0,
            position: 3,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653193,
            name: 'Пепперони',
            image: 'https://thumb.chocofood.kz/H4FQ9Fas1hypOcEvbkFBHy66C0M=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_F9i43jS.png',
            category: 66042,
            content: '',
            ingredients: '',
            price: 1590.0,
            discountPrice: 1590.0,
            position: 3,
            isActive: 1,
            note: 'n/a',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653271,
            name: 'Смузи клубничный 0,33 л',
            image: '',
            category: 66055,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 3,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653280,
            name: 'Какаон',
            image: '',
            category: 66056,
            content: '',
            ingredients: '',
            price: 690.0,
            discountPrice: 690.0,
            position: 3,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653254,
            name: 'Цитрусовый 1 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 1240.0,
            discountPrice: 1240.0,
            position: 3,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653261,
            name: 'Oreo Milkshake 0,33 л',
            image: '',
            category: 66052,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 3,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653266,
            name: 'Классический 0,4 л',
            image: '',
            category: 66054,
            content: '',
            ingredients: '',
            price: 790.0,
            discountPrice: 790.0,
            position: 4,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653211,
            name: 'Чесночный хлеб',
            image: '',
            category: 66045,
            content: '',
            ingredients: '',
            price: 490.0,
            discountPrice: 490.0,
            position: 4,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653189,
            name: 'Сладкая пицца с шоколадом и фруктами',
            image: 'https://thumb.chocofood.kz/MF5AIv2ydtzbvsPIiFvST424zpw=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_aINqwOF.png',
            category: 66042,
            content: '',
            ingredients: '',
            price: 1890.0,
            discountPrice: 1890.0,
            position: 4,
            isActive: 1,
            note: 'n/a',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653215,
            name: 'Красный бархат',
            image: '',
            category: 66046,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 4,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653279,
            name: 'Мокко',
            image: '',
            category: 66056,
            content: '',
            ingredients: '',
            price: 690.0,
            discountPrice: 690.0,
            position: 4,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653270,
            name: 'Смузи банановый 0,33 л',
            image: '',
            category: 66055,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 4,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653181,
            name: 'Классический Ice Tea 0,5 л',
            image: '',
            category: 66041,
            content: '',
            ingredients: '',
            price: 690.0,
            discountPrice: 690.0,
            position: 4,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653260,
            name: 'Бананово-молочный коктейль 0,33 л',
            image: '',
            category: 66052,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 4,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653253,
            name: 'Цитрусовый 0,5 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 740.0,
            discountPrice: 740.0,
            position: 4,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 722648,
            name: 'Алматинский донер 2',
            image: 'https://thumb.chocofood.kz/iHi8n_B9zgl-JcvH8LhKuyil0_g=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/09/07/food_ZcOcJBk.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1590.0,
            discountPrice: 1590.0,
            position: 4,
            isActive: 1,
            note: 'new',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653176,
            name: 'Sprite 0,5L',
            image: 'https://thumb.chocofood.kz/FVTcOBcSzC1bKI8Gk5Mj3A-DPJk=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_nWgfxKl.png',
            category: 66041,
            content: '',
            ingredients: '',
            price: 290.0,
            discountPrice: 290.0,
            position: 5,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653178,
            name: 'Fuse Tea 0.5L',
            image: 'https://thumb.chocofood.kz/yowp6cutUc1jBC8Rn0jNBOFyMBU=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_jptPV58.png',
            category: 66041,
            content: '',
            ingredients: '',
            price: 290.0,
            discountPrice: 290.0,
            position: 5,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653179,
            name: 'Сок Piko 0.2',
            image: 'https://thumb.chocofood.kz/xCvlm3hlmVAoAaXam2l6h2SwPCQ=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_ZSjgAUH.png',
            category: 66041,
            content: '',
            ingredients: '',
            price: 290.0,
            discountPrice: 290.0,
            position: 5,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653180,
            name: 'Айран',
            image: '',
            category: 66041,
            content: '',
            ingredients: '',
            price: 150.0,
            discountPrice: 150.0,
            position: 5,
            isActive: 1,
            note: 'popular',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653177,
            name: 'Coca-cola 0,5L',
            image: 'https://thumb.chocofood.kz/yntj8PwdLwiRF_IYjqyA7Ub88Vw=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_PEdNhHC.png',
            category: 66041,
            content: '',
            ingredients: '',
            price: 290.0,
            discountPrice: 290.0,
            position: 5,
            isActive: 1,
            note: 'popular',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653187,
            name: 'BBQ',
            image: 'https://thumb.chocofood.kz/R0s7DeaWQxtJ0g56O5bNBPfBTYY=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_koLjP2N.png',
            category: 66042,
            content: '',
            ingredients: '',
            price: 1790.0,
            discountPrice: 1790.0,
            position: 5,
            isActive: 1,
            note: 'n/a',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653278,
            name: 'Капучино',
            image: '',
            category: 66056,
            content: '',
            ingredients: '',
            price: 690.0,
            discountPrice: 690.0,
            position: 5,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 722647,
            name: 'Алматинский донер 1,5',
            image: 'https://thumb.chocofood.kz/j4zhkZdK1mmCPwuq1FeIDGocFKI=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/09/07/food_8RFiCLr.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1190.0,
            discountPrice: 1190.0,
            position: 5,
            isActive: 1,
            note: 'new',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653252,
            name: 'Клубника-маракуйя 1л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 1240.0,
            discountPrice: 1240.0,
            position: 5,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653259,
            name: 'Клубнично-молочный коктейль 0,33 л',
            image: '',
            category: 66052,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 5,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653210,
            name: 'Хлебная корзина',
            image: '',
            category: 66045,
            content: '',
            ingredients: '',
            price: 390.0,
            discountPrice: 390.0,
            position: 5,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653173,
            name: 'Flash up 0,45',
            image: '',
            category: 66041,
            content: '',
            ingredients: '',
            price: 390.0,
            discountPrice: 390.0,
            position: 5,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653174,
            name: 'Fanta 0,5L',
            image: 'https://thumb.chocofood.kz/V5I4Jwt3qXDxJgcPoHrB9triMjE=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_8C7qaCg.png',
            category: 66041,
            content: '',
            ingredients: '',
            price: 290.0,
            discountPrice: 290.0,
            position: 5,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653175,
            name: 'Bonaqua 0,5',
            image: 'https://thumb.chocofood.kz/sdBbyFXqMgKztjhOEy8GVibVP28=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_9IrIXf2.png',
            category: 66041,
            content: '',
            ingredients: '',
            price: 290.0,
            discountPrice: 290.0,
            position: 5,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 722646,
            name: 'Алматинский донер',
            image: 'https://thumb.chocofood.kz/7WmwZci-bnqoHsy6t5TSCAdVlGM=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/09/07/food_syiKXVM.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 6,
            isActive: 1,
            note: 'new',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653277,
            name: 'Латте',
            image: '',
            category: 66056,
            content: '',
            ingredients: '',
            price: 790.0,
            discountPrice: 790.0,
            position: 6,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653258,
            name: 'Шоколадно-молочный коктейль 0,33 л',
            image: '',
            category: 66052,
            content: '',
            ingredients: '',
            price: 990.0,
            discountPrice: 990.0,
            position: 6,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653186,
            name: 'Ранч',
            image: 'https://thumb.chocofood.kz/uHPR3LaXYLj_9i7PWcImCrIeIOk=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_Z7c1Ckk.png',
            category: 66042,
            content: '',
            ingredients: '',
            price: 1890.0,
            discountPrice: 1890.0,
            position: 6,
            isActive: 1,
            note: 'n/a',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653185,
            name: 'Flash up 0,33',
            image: '',
            category: 66041,
            content: '',
            ingredients: '',
            price: 290.0,
            discountPrice: 290.0,
            position: 6,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653251,
            name: 'Клубника-маракуйя 0,5 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 740.0,
            discountPrice: 740.0,
            position: 6,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653250,
            name: 'Ягодный 1 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 1240.0,
            discountPrice: 1240.0,
            position: 7,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653257,
            name: 'Молочный коктейль 0,33 л',
            image: '',
            category: 66052,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 7,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653191,
            name: 'Маргарита',
            image: 'https://thumb.chocofood.kz/bikQ-pDszfDaOsvEMPv1H_Z8SOY=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_0LlR2IN.png',
            category: 66042,
            content: '',
            ingredients: '',
            price: 1490.0,
            discountPrice: 1490.0,
            position: 7,
            isActive: 1,
            note: 'n/a',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653276,
            name: 'Американо',
            image: '',
            category: 66056,
            content: '',
            ingredients: '',
            price: 690.0,
            discountPrice: 690.0,
            position: 7,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653172,
            name: 'Фирменный донер',
            image: '',
            category: 66040,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 7,
            isActive: 1,
            note: 'popular',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653275,
            name: 'Двойной эспрессо',
            image: '',
            category: 66056,
            content: '',
            ingredients: '',
            price: 490.0,
            discountPrice: 490.0,
            position: 8,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653131,
            name: 'Фирменный донер 2',
            image: '',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1590.0,
            discountPrice: 1590.0,
            position: 8,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653249,
            name: 'Ягодный 0,5 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 740.0,
            discountPrice: 740.0,
            position: 8,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653132,
            name: 'Фирменный донер 1,5',
            image: '',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1190.0,
            discountPrice: 1190.0,
            position: 8,
            isActive: 1,
            note: 'popular',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653248,
            name: 'Киви-маракуйя 1 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 1240.0,
            discountPrice: 1240.0,
            position: 9,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653274,
            name: 'Эспрессо',
            image: '',
            category: 66056,
            content: '',
            ingredients: '',
            price: 390.0,
            discountPrice: 390.0,
            position: 9,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653140,
            name: 'Донер на тарелке говяжий',
            image: 'https://thumb.chocofood.kz/qOZ9NWuwY7a8ZaC-X1WzxGJg_5w=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_XPpC3fc.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1590.0,
            discountPrice: 1590.0,
            position: 10,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653247,
            name: 'Киви-маракуйя 0,5 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 740.0,
            discountPrice: 740.0,
            position: 10,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653163,
            name: 'Донер в батоне Куриный',
            image: 'https://thumb.chocofood.kz/92XOiYGwl8w_oyWyA2f2HdU7IVg=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_wqjws4u.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 10,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653139,
            name: 'Донер грибной 1,5',
            image: 'https://thumb.chocofood.kz/2Gmckx3cqevviviJyFZMuLD9oW4=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_rBYqyjn.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1190.0,
            discountPrice: 1190.0,
            position: 10,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653155,
            name: 'Донер грибной',
            image: 'https://thumb.chocofood.kz/BURticCXDGNYTYWtgSQ5UiA1IHs=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/03/26/food_3MLNRus.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 10,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653153,
            name: 'Angry Донер Куриный (острый)',
            image: 'https://thumb.chocofood.kz/Unhb4aLIV0Wcot5GgBdb-17GDpk=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_jGgA6cE.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 10,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653154,
            name: 'Angry Донер Куриный 2  (острый)',
            image: 'https://thumb.chocofood.kz/JqlsV6qlGXx4yL-T_6k2KgA5-Hc=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_S2iH3N8.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1590.0,
            discountPrice: 1590.0,
            position: 10,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653141,
            name: 'Донер на тарелке Ассорти',
            image: 'https://thumb.chocofood.kz/tdGzUwbTCE-gJ9eEyIFst_XB_TM=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_GEG3efZ.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1590.0,
            discountPrice: 1590.0,
            position: 10,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653246,
            name: 'Киви 1 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 1240.0,
            discountPrice: 1240.0,
            position: 11,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653160,
            name: 'Донер в батоне Говяжий',
            image: 'https://thumb.chocofood.kz/5OxV6XoBU3YoQw7HmvVkdZ1yxW0=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_tyA7Wzu.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 11,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653245,
            name: 'Киви 0,5 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 740.0,
            discountPrice: 740.0,
            position: 12,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653162,
            name: 'Донер в батоне Ассорти',
            image: 'https://thumb.chocofood.kz/AcRgzQZPCLaLXZ820Ue1aua_OLo=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_vDHOFRS.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 13,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653244,
            name: 'Классический 1 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 1140.0,
            discountPrice: 1140.0,
            position: 13,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653243,
            name: 'Классический 0,5 л',
            image: '',
            category: 66051,
            content: '',
            ingredients: '',
            price: 740.0,
            discountPrice: 740.0,
            position: 14,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
        {
            id: 653167,
            name: 'Angry Донер Говяжий  (острый)',
            image: 'https://thumb.chocofood.kz/U0crKgFaj1lP-UcaKmjksXimAI8=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_pieWbVu.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 22,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653171,
            name: 'Angry Донер Ассорти  (острый)',
            image: 'https://thumb.chocofood.kz/aSKrXMS7l5njFVKuR4NYfJvu0VE=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_qNiGDA8.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 890.0,
            discountPrice: 890.0,
            position: 23,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653169,
            name: 'Angry Донер Говяжий 1,5  (острый)',
            image: 'https://thumb.chocofood.kz/iVkw95HUeEfxWoXSFubcw3kkgkE=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_VOA6k7F.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1190.0,
            discountPrice: 1190.0,
            position: 24,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653168,
            name: 'Angry Донер Куриный 1,5  (острый)',
            image: 'https://thumb.chocofood.kz/ltg_2EACBZUA0_mw9AxtoTnyAdM=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_Jz6hizR.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1190.0,
            discountPrice: 1190.0,
            position: 25,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653143,
            name: 'Angry Донер Ассорти 2  (острый)',
            image: 'https://thumb.chocofood.kz/dDXvGQ6mqDzk5OZynMVxaGExFbM=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_QkzBo57.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1590.0,
            discountPrice: 1590.0,
            position: 28,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653166,
            name: 'Angry Донер Ассорти 1,5  (острый)',
            image: 'https://thumb.chocofood.kz/CLOSuvX5ImqQ4P1WVeYHSjBCUzU=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_PHAoiL6.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1190.0,
            discountPrice: 1190.0,
            position: 29,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653170,
            name: 'Angry донер Говяжий 2 (острый)',
            image: 'https://thumb.chocofood.kz/j1YrCGsp9_bcxFCqqrdueFWSni8=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_W7I6f7v.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1590.0,
            discountPrice: 1590.0,
            position: 32,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: true,
        },
        {
            id: 653164,
            name: 'Донер на тарелке куриный',
            image: 'https://thumb.chocofood.kz/_jfThmKgZEq2OgodxoCnqqJPqW0=/fit-in/640x640/https://chocofood.kz/media/site/restaurants/food/logo/2020/01/10/food_xM9DqU2.png',
            category: 66040,
            content: '',
            ingredients: '',
            price: 1590.0,
            discountPrice: 1590.0,
            position: 47,
            isActive: 1,
            note: '',
            specialty: '',
            rate: 3 + Math.round(Math.random() * 2),
            likes: Math.round(Math.random() * 300),
            isAlcohol: false,
            hasModification: false,
        },
    ];

  constructor() {
      for (let i = 0; i < 10; i++) {
          let category = new Category();
          category.name = 'SOGUK ICECEKLER' + i;
          category.mainmedia = 'https://www.cardinalmarkt.com/class/INNOVAEditor/assets/soguk.jpg';
          category.items = [];
          category.order = i;

          for (let j = 0; j < 10; j++) {
              let item = new Item();
              item.id = i.toString() + j.toString();
              item.rate = 3 + Math.round(Math.random() * 2);
              item.likes = Math.round(Math.random() * 300);
              item.name = 'Latte Machiatto Latte Machiatto';
              item.image = 'https://www.645kk.com/wp-content/uploads/2017/07/CAFE-LATTE.jpg';
              item.price = 20.00;
              item.content = '';
              item.order = j;

              category.items.push(item);
          }
      }
  }

    menu = {
        currency: 'TL',
        categories: [],
    };

    // constructor() {
    //     this.menu.categories = this.categories.sort((a, b) => a.position - b.position);
    //     this.menu.categories = this.menu.categories.map(category => {
    //         category.items = this.products.filter(item => item.category === category.id).map(item => {
    //             item.content = item.content || 'Описание отсутствует';
    //             item.image = item.image || 'https://www.fitleziz.com/upload/hedefinizi_belirleyin.png';
    //             return item;
    //         }).sort((a, b) => a.position - b.position);
    //         return category;
    //     });
    // }
    getCategories() {
        return this.menu.categories;
    }
}

